application: 
version: 1
runtime: go
api_version: go1

handlers:
- url: /rsvpmyevents
  script: _go_app
  login: admin
- url: /rsvpeventworker
  script: _go_app
  login: admin
- url: /.*
  script: _go_app